package com.assignment.transaction.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * JPA entity representing a financial account.
 *
 * <h3>Design Decisions</h3>
 * <ul>
 *   <li><b>BigDecimal for balance</b>: {@code double}/{@code float} introduce floating-point
 *       rounding errors (e.g., {@code 0.1 + 0.2 ≠ 0.3}). Financial calculations require exact
 *       decimal arithmetic — {@code BigDecimal} guarantees this.</li>
 *   <li><b>precision=19, scale=4</b>: Supports values up to 999,999,999,999,999.9999
 *       — sufficient for any realistic financial amount with 4 decimal places.</li>
 *   <li><b>IDENTITY strategy</b>: Uses the database's auto-increment feature. H2 and
 *       PostgreSQL both support this natively. Simpler than SEQUENCE for this use case.</li>
 *   <li><b>@Version for optimistic locking</b>: Prevents lost updates when concurrent
 *       transactions read the same account. Works alongside pessimistic locking in the
 *       repository for defense-in-depth concurrency control.</li>
 *   <li><b>No @ManyToOne on Transaction</b>: The assignment stores {@code sourceAccountId}
 *       and {@code targetAccountId} as plain {@code Long} fields. This is intentional for
 *       high-throughput systems — avoids eager loading, N+1 queries, and bidirectional
 *       relationship complexity.</li>
 * </ul>
 */
@Entity
@Table(name = "account")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Account {

    /**
     * Primary key — auto-generated by the database.
     * Matches the IDs used in data.sql (1–10).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Full name of the account holder.
     * Cannot be null or empty — enforced at the database level.
     */
    @Column(name = "owner_name", nullable = false)
    private String ownerName;

    /**
     * Current account balance in the specified currency.
     * Uses BigDecimal for exact decimal arithmetic.
     * Cannot be null — defaults should be set via data.sql or application logic.
     */
    @Column(name = "balance", nullable = false, precision = 19, scale = 4)
    private BigDecimal balance;

    /**
     * ISO 4217 currency code (e.g., USD, EUR, GBP).
     * Stored as a 3-character string rather than an enum to support
     * future currency additions without code changes.
     */
    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    /**
     * Optimistic lock version field.
     * Hibernate auto-increments this on every UPDATE — if two transactions
     * read version=1 and both try to write version=2, the second one gets
     * an {@code OptimisticLockException}, preventing lost updates.
     */
    @Version
    private Long version;
}
