package com.assignment.transaction.entity;

import com.assignment.transaction.model.TransactionStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * JPA entity representing a single financial transaction (money transfer).
 *
 * <h3>Design Decisions</h3>
 * <ul>
 *   <li><b>Plain Long IDs instead of @ManyToOne</b>: {@code sourceAccountId} and
 *       {@code targetAccountId} are stored as plain foreign key values. In a high-throughput
 *       batch processor, this avoids Hibernate's lazy-loading proxies, N+1 queries, and
 *       bidirectional relationship management overhead.</li>
 *   <li><b>EnumType.STRING for status</b>: Stores "SUCCESS", "FAILED", "PENDING" as readable
 *       strings. Ordinal storage (0, 1, 2) is fragile — adding a new status shifts all values
 *       and silently corrupts existing rows.</li>
 *   <li><b>batchId as String (UUID)</b>: Groups all transactions submitted in a single API call.
 *       Indexed for fast batch-level queries (e.g., "show me all transactions from batch X").</li>
 *   <li><b>failureReason</b>: Human-readable explanation stored directly on the entity, so
 *       clients can retrieve failure details without parsing logs or exception traces.</li>
 *   <li><b>Database indexes</b>: {@code batchId} and {@code sourceAccountId} are indexed
 *       because they're used in grouping (Collectors.groupingBy) and batch lookup queries.</li>
 * </ul>
 */
@Entity
@Table(name = "transaction", indexes = {
        @Index(name = "idx_transaction_batch_id", columnList = "batch_id"),
        @Index(name = "idx_transaction_source_account", columnList = "source_account_id"),
        @Index(name = "idx_transaction_status", columnList = "status")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Transaction {

    /**
     * Primary key — auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Account ID from which funds are debited.
     * Stored as a plain Long — not a JPA relationship (see class-level Javadoc).
     */
    @Column(name = "source_account_id")
    private Long sourceAccountId;

    /**
     * Account ID to which funds are credited.
     */
    @Column(name = "target_account_id")
    private Long targetAccountId;

    /**
     * Transfer amount. Must be positive for valid transactions.
     * Failed transactions (negative/zero amounts) are also persisted
     * with status=FAILED for audit purposes.
     */
    @Column(name = "amount", precision = 19, scale = 4)
    private BigDecimal amount;

    /**
     * Current processing status of this transaction.
     * Stored as a VARCHAR (e.g., "PENDING") via EnumType.STRING.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    private TransactionStatus status;

    /**
     * Timestamp of when the transaction was initiated by the client.
     * Used for deduplication — two transactions with the same source,
     * target, amount, and timestamp within 2 seconds are considered duplicates.
     */
    @Column(name = "timestamp")
    private LocalDateTime timestamp;

    /**
     * Human-readable reason for failure (null if status != FAILED).
     * Examples: "Insufficient balance", "Duplicate Transaction", "Account not found".
     */
    @Column(name = "failure_reason")
    private String failureReason;

    /**
     * UUID linking this transaction to the batch it was submitted in.
     * All transactions from a single POST request share the same batchId.
     */
    @Column(name = "batch_id")
    private String batchId;
}
